version: "3"
services:
  postgres:
    image: postgres:13.7
    environment:
      POSTGRES_DB: explorer
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"

  redis:
    image: redis:7.0.4
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"

  little_bigtable:
    build:
      dockerfile: ./docker/little_bigtable/Dockerfile
    image: little_bigtable
    command: little_bigtable -db-file /app/little_bigtable.db -host 0.0.0.0 -port 8086
    ports:
      - "8086:8086"
    volumes:
      - "./data/little_bigtable:/app"
